### ISSUE TITLE
Request Firebase access

### ISSUE THREAD

**Issue by YungiKim1999** [SE701Group2/daily-focus#114]
**Developer Story**
As a developer, I want access to the firebase console (https://console.firebase.google.com/u/2/project/daily-focus-a7423/overview), used by the server in order to run and modify the server.

**Acceptance Criteria**
I should be added as a member in https://console.firebase.google.com/u/2/project/daily-focus-a7423/settings/iam
with the email address: se701group5.uoa@gmail.com

**Comment by Jennak21** [comment]
Hey Daniel, I have added you to the firebase. An invite should have been sent 👍

**Comment by lucas2005gao** [comment]
![image](https://user-images.githubusercontent.com/48196609/114677489-788e2400-9d5e-11eb-9458-b7a26d12d3ae.png)
@Jennak21 Hey Jenna! Is the gmail account binded to your phone for TFA?

**Comment by lucas2005gao** [comment]
![image](https://user-images.githubusercontent.com/48196609/114678009-f18d7b80-9d5e-11eb-8a23-09a4c4bfe68f.png)
@Jennak21 Hey Jenna! Is the gmail account binded to your phone for TFA?

**Comment by lucas2005gao** [comment]
Nvm!! Sorry! Just found out it's binded to Daniel's phone
