### ISSUE TITLE
NewsWidget test fails

### ISSUE THREAD

**Issue by brickahax** [SE701Group2/daily-focus#126]
**Describe the bug**
NewsWidget is failing tests when articles are returned by the API with null authors

**Steps To Reproduce**
Run the NewsWiget.test.js test suite. "the data is returned from the getArticles function (API endpoint works)" test fails if by chance there is no author returned in the JSON data for the article.

**Screenshots**  
![image](https://user-images.githubusercontent.com/13882258/115335196-d2746b00-a1f0-11eb-9568-fe6d921d3df5.png)

**Expected behavior**
Test passes

**How to fix**
Allow for unimportant fields to be returned as null by the API in tests

**Comment by DanielDowling999** [comment]
So, the reason it's complaining is that you're getting a string back instead of an object? Is the author supposed to be an object, and not a string?

**Comment by brickahax** [comment]
> So, the reason it's complaining is that you're getting a string back instead of an object? Is the author supposed to be an object, and not a string?

Yeah, I believe null was being returned alot, and as null is counted as an object type the original author of the test suit thought that the author was supposed to be an object type, whereas when it is returned correctly it is actually a string type.
