### ISSUE TITLE
Create a static component that show current weather in Auckland

### ISSUE THREAD

**Issue by Jigao-Zeng** [SE701Group2/daily-focus#15]
**User Story**
As a user, I want a widget that tells me what the weather is like at a given location.

**Acceptance Criteria**
* A weather component that shows the current weather in Auckland
* On hover, the component expands and shows the weather for the next 12 hours (see Figma design)

**Additional Context**
Figma Link: https://www.figma.com/file/J2DDVa9redQigCzTee56xw/SE701-Daily-Focus?node-id=0%3A1

**Comment by Denijar** [comment]
@Jigao-Zeng I wonder if the scope of this issue is too big? Maybe this issue can be for creating a static component that shows today's weather. Then another issue can be created to adds the "on hover" functionality.

**Comment by Jigao-Zeng** [comment]
Yes, I agree, thanks for letting me know the details by the way.
