### ISSUE TITLE
Create the calendar widget  

### ISSUE THREAD

**Issue by mikeFam** [SE701Group2/daily-focus#16]
**User Story**
As a user, I want to see a calendar that shows me my events for the day.

**Acceptance Criteria**
* Add/remove/update events 
* Different views, eg. monthly, weekly, etc...
* Link with Google Calendar API

**Additional Context**
Figma Link: https://www.figma.com/file/J2DDVa9redQigCzTee56xw/SE701-Daily-Focus?node-id=32%3A3

**Comment by Denijar** [comment]
Looks good, and the design looks nice. It might be worth clarifying the scope of this issue (though I realise that this is changing as you do more research).
