### ISSUE TITLE
Clean up create-react-app auto-generated files

### ISSUE THREAD

**Issue by Denijar** [SE701Group2/daily-focus#3]
**Developer Story**
As a developer, I want the contents of public folder, reportWebVitals.js, and stock react logos to be cleaned up and to match the theme of our project.

**Acceptance Criteria**
* remove the reportWebVitals.js file - and remove the call to reportWebVitals() in the client/index.js file and the commenting
* delete the package-lock.json in the root directory
* replace favicon.ico and logo192.png with the focus target logo
* Change the name of the app from "React App" to "Focus" in the index.html

**Additional Context**
Logo images can be found in the #design Discord.

Figma link: https://www.figma.com/file/J2DDVa9redQigCzTee56xw/SE701-Daily-Focus?node-id=0%3A1

**Comment by dikunong** [comment]
README task also covered in #24
