### ISSUE TITLE
Login endpoint does not work for incorrect username or password

### ISSUE THREAD

**Issue by Jennak21** [SE701Group2/daily-focus#56]
**Describe the bug**
When an incorrect password or email is sent in the request for "/login", no response is received

**Steps To Reproduce**
Either: enter an incorrect password or username in the request for "/login"

**Screenshots**  
[Screenshots/screen recordings of the bug]
![image](https://user-images.githubusercontent.com/52437731/111531424-62299280-87c9-11eb-9654-d7029c10d61e.png)
![image](https://user-images.githubusercontent.com/52437731/111531463-71104500-87c9-11eb-96cb-4564a07d4bd4.png)

**Expected behavior**
A 401 unauthorized response

**How to fix**
delete the console.log(err)
Would be good to change line 32 to 
```         
return res.status(401).json({ message: err.message });
```
and delete validation checks

**Additional Information**

**Comment by Pranavan10** [comment]
just change console.err to console.error and it works I believe
