### ISSUE TITLE
Make a minimum to-do list

### ISSUE THREAD

**Issue by tommyshi55** [SE701Group2/daily-focus#6]
**User Story**
As a user, I want a to do list that I add items to and which I can check off as completed.

**Acceptance Criteria**
* A to do list component with items that can be checked off
* A way to add items to the list
* Able to persist the items after reload - browser storage for now

**Additional Context**
Figma Link: https://www.figma.com/file/J2DDVa9redQigCzTee56xw/SE701-Daily-Focus?node-id=0%3A1

In future, this component will be integrated with the backend so the list can sync across multiple computers. However, for this minimum component, the goal is for it to simply be stored in browser storage.

**Comment by Denijar** [comment]
This issue looks good. It might be worth creating a new issue for connecting the to-do list to the backend. You also might need to get some clarification from the design team about what the interface for adding new to list items is. If it is a modal, you should add that to the acceptance criteria.
