### ISSUE TITLE
Remove extra app.js code causing issues

### ISSUE THREAD

**Issue by raymondhonsumchiu** [SE701Group2/daily-focus#69]
**Describe the bug**
There is extra code in app.js that:
Causes the server to run on localhost:3000 instead of 9000 which conflicts with the front-end port

**Steps To Reproduce**
Run:
```node app.js```
This will cause the server to run on port 3000.

**Expected behavior**
The server should run on port 9000.

**How to fix**
Remove the unnecessary lines of code in app.js

**Comment by Jennak21** [comment]
👍
