### ISSUE TITLE
Make a small game

### ISSUE THREAD

**Issue by ggao007** [SE701Group2/daily-focus#8]
**User Story**
As a user, I want to get some points when I finish one task, then I can use these points to water trees(Planting trees game), and then the trees can be more beautiful and big.

**Acceptance Criteria**
* The progress bar will show the growth progress of the trees.
* The picture shows the tree. For example, when the progress bar reaches 10%, we will change another picture with a bigger tree to make it as growth progress.
* A button that, when clicked, the points will be reduced and the progress bar will be increased.
* These features are inside of a pop-up modal
* A small button (the same size as the todo list plus button) is created that, when clicked, shows the modal

**Comment by Denijar** [comment]
@ggao007 I think that this issue needs to be fleshed out more. I think there needs to be a more clear user story and acceptance criteria before work should start on this feature.

**Comment by ggao007** [comment]
I add the user story in the issues, so u can see that. If u have some
confusions, we can discuss it.

Denise ***@***.***> 于2021年3月13日周六 下午2:21写道：

**Comment by Denijar** [comment]
Okay awesome that seems like you have a clear direction to follow. Love the idea :D. Can you please edit this issue so that it follows the Enhancement issue format (see https://github.com/SE701Group2/daily-focus/wiki/Issues)

**Comment by ggao007** [comment]
I finished that, I have a few experiences with writing that, I am not sure
that is good enough, so plz check my comments, is there anything I need
to change?

Denise ***@***.***> 于2021年3月13日周六 下午4:06写道：
